name: Trigger auto deployment for ca-clinigenos-track-prod-001

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/ca-clinigenos-track-prod-001-AutoDeployTrigger-0d792254-2889-43c0-bc9f-1faf1d0b883d.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: clinigenosacr.azurecr.io
          username: ${{ secrets.CACLINIGENOSTRACKPROD001_REGISTRY_USERNAME }}
          password: ${{ secrets.CACLINIGENOSTRACKPROD001_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: clinigenosacr.azurecr.io/ca-clinigenos-track-prod-001:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CACLINIGENOSTRACKPROD001_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n ca-clinigenos-track-prod-001 -g rg-clinigenos-app-prod-001 --server clinigenosacr.azurecr.io --username  ${{ secrets.CACLINIGENOSTRACKPROD001_REGISTRY_USERNAME }} --password ${{ secrets.CACLINIGENOSTRACKPROD001_REGISTRY_PASSWORD }}
            az containerapp update -n ca-clinigenos-track-prod-001 -g rg-clinigenos-app-prod-001 --image clinigenosacr.azurecr.io/ca-clinigenos-track-prod-001:${{ github.sha }}
